name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vhdl_standard: [ "1993", "2002", "2008", "2019" ]
    steps:
      - name: Install prerequisites
        run: "sudo apt-get install -y llvm-dev"

      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build everything (root)
        run: "bazel build //... --@rules_vunit//:vhdl_standard=${{ matrix.vhdl_standard }}"
      - name: Build everything (integration)
        run: "cd integration && bazel build //... --@rules_vunit//:vhdl_standard=${{ matrix.vhdl_standard }}"
      - name: Test everything (root)
        if: ${{ matrix.vhdl_standard == '2008' || matrix.vhdl_standard == '2019' }}
        run: "bazel test //... --@rules_vunit//:vhdl_standard=${{ matrix.vhdl_standard }}"
      - name: Test everything (integration)
        if: ${{ matrix.vhdl_standard == '2008' || matrix.vhdl_standard == '2019' }}
        run: "cd integration && bazel test //... --@rules_vunit//:vhdl_standard=${{ matrix.vhdl_standard }}"
